name: edge_io
description: IO implementations for Dart Edge.
homepage: https://dartedge.dev
repository: https://github.com/invertase/dart_edge/tree/main/packages/edge_io
version: 0.0.1-dev.1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  file: ^6.1.4
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.1